### ISSUE TITLE
job_start(cmd) cannot work

### ISSUE THREAD

**Issue by Freed-Wu** [voldikss/vim-browser-search#11]
OS: Gentoo/Linux
vim: gvim-8.2.0114

`call job_start("xdg-open 'https://google.com/search?q=hello'")` cannot work.
`call job_start("xdg-open https://google.com/search?q=hello")` can work.

`call system("xdg-open 'https://google.com/search?q=hello'")` 
and `call system("xdg-open https://google.com/search?q=hello")` both can work.

this makes this plugin cannot work because
```
  if exists('*jobstart')
    call jobstart(cmd)
  elseif exists('*job_start')
    call job_start(cmd)
  else
    call system(cmd)
  endif
```
when cmd is `xdg-open 'https://google.com/search?q=hello'`

i think this error don't come from this plugin. perhaps you can provide a variable to allow user to choose `job_start` or `system` to avoid it?

Thank you. May the source be with you.

**Comment by voldikss** [comment]
Thanks, fixed.
