### ISSUE TITLE
Does not automatically close the browser

### ISSUE THREAD

**Issue by pacmanzou** [voldikss/vim-browser-search#13]
你好 
文件关闭时，被打开的浏览器也会关闭，如何让它不关闭呢？（不考虑事先打开浏览器）

**Comment by voldikss** [comment]
我这里不会出现呢这个问题，而且理论上不会出现这个问题的

**Comment by voldikss** [comment]
提供一下 vim/nvim，浏览器，OS的版本

**Comment by pacmanzou** [comment]
nvim 0.4.4 
chromium 版本 84.0.4147.125（正式版本）Arch Linux （64 位）
manjaro 是最新的长期支持版本的内核 
i3wm

**Comment by pacmanzou** [comment]
就是个小问题 只不过我以后就要先打开浏览器再开neovim了 哈哈

**Comment by voldikss** [comment]
emmm 这个环境有点特殊:joy:

只是我暂时还不能确定哪里出问题了

**Comment by voldikss** [comment]
i3wm 的话，你是不是没装桌面环境只装了窗口管理器

我没用过窗口管理器，不知道是不是这个导致的

**Comment by pacmanzou** [comment]
嗯 依然感谢你 很喜欢你的插件 哈哈

**Comment by pacmanzou** [comment]
对的 只有一个i3wm 可能就是它的原因
